/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminTrustRouteImport } from './routes/admin.trust'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWhyRouteImport } from './routes/admin.why'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.blog.lazy').then((d) => d.Route))
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.content.lazy').then((d) => d.Route))
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.dashboard.lazy').then((d) => d.Route),
)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/admin/faq',
  path: '/admin/faq',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.faq.lazy').then((d) => d.Route))
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/admin/fleet',
  path: '/admin/fleet',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.fleet.lazy').then((d) => d.Route))
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.gallery.lazy').then((d) => d.Route))
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.login.lazy').then((d) => d.Route))
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.messages.lazy').then((d) => d.Route),
)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.seo.lazy').then((d) => d.Route))
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.services.lazy').then((d) => d.Route),
)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.settings.lazy').then((d) => d.Route),
)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.team.lazy').then((d) => d.Route))
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.testimonials.lazy').then((d) => d.Route),
)
const AdminTrustRoute = AdminTrustRouteImport.update({
  id: '/admin/trust',
  path: '/admin/trust',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.trust.lazy').then((d) => d.Route))
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.users.lazy').then((d) => d.Route))
const AdminWhyRoute = AdminWhyRouteImport.update({
  id: '/admin/why',
  path: '/admin/why',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.why.lazy').then((d) => d.Route))
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application': typeof ApplicationRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/why': typeof AdminWhyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application': typeof ApplicationRoute
  '/contact': typeof ContactRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/why': typeof AdminWhyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application': typeof ApplicationRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/why': typeof AdminWhyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/application'
    | '/blog'
    | '/contact'
    | '/services'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/faq'
    | '/admin/fleet'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/trust'
    | '/admin/users'
    | '/admin/why'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/application'
    | '/contact'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/faq'
    | '/admin/fleet'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/trust'
    | '/admin/users'
    | '/admin/why'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/application'
    | '/blog'
    | '/contact'
    | '/services'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/faq'
    | '/admin/fleet'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/trust'
    | '/admin/users'
    | '/admin/why'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationRoute: typeof ApplicationRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AdminBlogRoute: typeof AdminBlogRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTrustRoute: typeof AdminTrustRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWhyRoute: typeof AdminWhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/admin/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/admin/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trust': {
      id: '/admin/trust'
      path: '/admin/trust'
      fullPath: '/admin/trust'
      preLoaderRoute: typeof AdminTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/why': {
      id: '/admin/why'
      path: '/admin/why'
      fullPath: '/admin/why'
      preLoaderRoute: typeof AdminWhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationRoute: ApplicationRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AdminBlogRoute: AdminBlogRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTrustRoute: AdminTrustRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWhyRoute: AdminWhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
